id: I1B15A0A5
ocr_import_info:
  timestamp: '2023-07-10T12:44:33.809689+00:00'
  batch_id: batch-4e3c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-10 12:51:02.635384+00:00
last_modified: 2023-07-10 12:51:02.635393+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W22087
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22087
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་འདུལ་བ་མདོ་རྩ།
  languages:
  - bo
  author: སློབ་དཔོན་ཡོན་ཏན་འོད།
statistics:
  ocr_word_mean_confidence_index: 0.9568337075473675
  ocr_word_median_confidence_index: 0.9977521
bases:
  I1KG8859:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8859
      total_pages: 260
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8859.txt
    statistics:
      ocr_word_median_confidence_index: 0.9977521
      ocr_word_mean_confidence_index: 0.9568337075473675
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
